# ------------------------------------
# SITE INFO SETTINGS

title: Public Safety Council Zone 6
#subtitle: Public Safety Council Zone 6
email: PSCZSIX@gmail.com
description: We are Pittsburgh Public Safety Council Zone 6
#baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://mhowe0422.github.io"
author:
street_address: 
city: Pittsburgh
state: PA
zip_code: 55555
country: United States of America
phone: (412) 555-5555

# Social media
github_url: https://github.com/mhowe0422
twitter_url: https://twitter.com/PSCZSIX
meetup_url: 
slack_url: 
500px_url:
facebook_url: https://www.facebook.com/PSCZSIX
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:


# Logos
logo:
  banner: /assets/images/logos/banner.svg
  banner-white: /assets/images/logos/banner-white.svg
  banner-img: /assets/images/logos/banner.png
  icon-banner: /assets/images/logos/icon-banner.svg
  icon: /assets/images/logos/icon.svg

# ------------------------------------
# SITE CONFIG SETTINGS

sass:
    sass_dir: _sass
    
# post publication settings
future: false

# COLLECTIONS
collections:
  projects:
    output: true

# Build settings
markdown: kramdown
permalink: pretty
